# 文件：.github/workflows/sync.yaml
name: Upstream Sync

permissions:
  contents: write
  issues: write

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}

      - name: Clean issue notice
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issues'
          labels: '🚨 Sync Fail'
          token: ${{ secrets.BOT_TOKEN }}

      - name: Sync upstream changes
        id: sync
        run: |
          git config user.name "Geekertao-bot"
          git config user.email "Geekertao@qq.com"
          git remote add upstream https://github.com/komari-monitor/komari-document.git
          git fetch upstream main
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          git push origin main

      - name: Sync check
        if: failure()
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-issue'
          title: '🚨 同步失败 | Sync Fail'
          labels: '🚨 Sync Fail'
          body: |
            Due to a change in the workflow file of the [komari-document][upstream] upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork.
            由于 [komari-document][upstream] 上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次。
            [upstream]: https://github.com/komari-monitor/komari-document
          token: ${{ secrets.BOT_TOKEN }}
